### ISSUE TITLE
Device settings can not be used

### ISSUE THREAD

**Issue by vuanh1408** [epodegrid/epd106-ADB#11]
Hi. I followed your guide on installing English interface and apps for Inkpalm 5. Everything works fine, but the Device Settings in Settings can not be used. It's used to set password, time, how long devices automatically turn off etc... When I try to click on it, it keeps showing Settings has stopped. Can u check this? Thank a lot in advanced

**Comment by heysirajum** [comment]
Hi, is there a way to install Playstore in mireader?

**Comment by alexxed** [comment]
the error is 
```json
12-16 14:59:10.782  3363  3363 E AndroidRuntime: FATAL EXCEPTION: main
12-16 14:59:10.782  3363  3363 E AndroidRuntime: Process: com.mgs.settings, PID: 3363
12-16 14:59:10.782  3363  3363 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mgs.settings/com.mgs.settings.DevicesSettingsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
12-16 14:59:10.782  3363  3363 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
12-16 14:59:10.782  3363  3363 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
12-16 14:59:10.782  3363  3363 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
12-16 14:59:10.782  3363  3363 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
12-16 14:59:10.782  3363  3363 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-16 14:59:10.782  3363  3363 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
12-16 14:59:10.782  3363  3363 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6496)
12-16 14:59:10.782  3363  3363 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-16 14:59:10.782  3363  3363 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
12-16 14:59:10.782  3363  3363 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
12-16 14:59:10.782  3363  3363 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setVisibility(int)' on a null object reference
12-16 14:59:10.782  3363  3363 E AndroidRuntime: 	at com.mgs.settings.DevicesSettingsActivity.onCreate(DevicesSettingsActivity.java:92)
12-16 14:59:10.782  3363  3363 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7030)
12-16 14:59:10.782  3363  3363 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7021)
12-16 14:59:10.782  3363  3363 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
12-16 14:59:10.782  3363  3363 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
12-16 14:59:10.782  3363  3363 E AndroidRuntime: 	... 9 more
12-16 14:59:10.530  1904  2019 D ActivityStack: isSystemReady
12-16 14:59:10.792  1904  2019 W ActivityManager:   Force finishing activity com.mgs.settings/.DevicesSettingsActivity
12-16 14:59:10.797  1904  2019 W ActivityManager:   Force finishing activity com.mgs.settings/.MgsSettingsActivity
12-16 14:59:10.804  1904  1919 I ActivityManager: Showing crash dialog for package com.mgs.settings u0
```

**Comment by alexxed** [comment]
If you uninstall the custom launcher, device settings works again (but it's in chinese).
